// Generate crates/ui/src/icon_name.rs from the files in assets/icons.
// Run after tools/build_icons.mjs.
import { readdirSync, writeFileSync } from "node:fs";

import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const DIR = join(root, "assets/icons");
const files = readdirSync(DIR).filter((f) => f.endsWith(".svg"));
const duo = new Set(
  files.filter((f) => f.endsWith(".duo.svg")).map((f) => f.slice(0, -8))
);
const names = files
  .filter((f) => !f.endsWith(".duo.svg"))
  .map((f) => f.slice(0, -4))
  .sort();

const variant = (n) =>
  n
    .split("-")
    .map((p) => p[0].toUpperCase() + p.slice(1))
    .join("");

const out = `//! Generated by \`node tools/gen_icon_enum.mjs\`. Do not edit.
//!
//! One variant per file in \`assets/icons\`. \`has_duo_layer\` reports whether a
//! second \`<name>.duo.svg\` exists, which [\`crate::Icon\`] stacks underneath the
//! primary layer to fake duotone — gpui tints an SVG with a single colour.

use gpui::SharedString;

/// Every icon shipped with the app.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub enum IconName {
${names.map((n) => `    ${variant(n)},`).join("\n")}
}

impl IconName {
    /// Stable kebab-case name, matching the file stem.
    pub fn name(self) -> &'static str {
        match self {
${names.map((n) => `            Self::${variant(n)} => "${n}",`).join("\n")}
        }
    }

    /// Asset path of the primary layer.
    pub fn path(self) -> SharedString {
        SharedString::new_static(match self {
${names.map((n) => `            Self::${variant(n)} => "icons/${n}.svg",`).join("\n")}
        })
    }

    /// Asset path of the secondary layer, for the duotone icons.
    pub fn duo_path(self) -> Option<SharedString> {
        Some(SharedString::new_static(match self {
${names
  .filter((n) => duo.has(n))
  .map((n) => `            Self::${variant(n)} => "icons/${n}.duo.svg",`)
  .join("\n")}
            _ => return None,
        }))
    }

    /// Whether this icon has a second layer.
    pub fn has_duo_layer(self) -> bool {
        self.duo_path().is_some()
    }

    /// All icons, for the gallery in \`examples/gallery.rs\`.
    pub const ALL: &'static [IconName] = &[
${names.map((n) => `        IconName::${variant(n)},`).join("\n")}
    ];
}
`;

writeFileSync(join(root, "crates/ui/src/icon_name.rs"), out);
console.log(`${names.length} icons, ${duo.size} with a duo layer`);
